# Generated by Django 5.2.8 on 2025-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kegiatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("waktu_mulai", models.TimeField()),
                ("waktu_selesai", models.TimeField()),
                ("nama", models.CharField(max_length=255)),
                ("tempat", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
            ],
            options={
                "ordering": ["tanggal", "waktu_mulai"],
            },
        ),
    ]
